### ISSUE TITLE
DA_faster  evaluate on clipart score is higher than your papers

### ISSUE THREAD

**Issue by aiboys** [VisionLearningGroup/DA_Detection#42]
Hi,
  I use this [open-source code](https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch)  to evaluate da_faster on voc-clipart.
The dataset I used as follows:
source dataset: VOC07+12 trainval, 16k images all.
target dataset: clipart1k (train+test)

And I got higher score(voc07 metric, IoU=0.5) than your papers:
```yaml
mAP: 0.3296
aeroplane       : 0.2564
bicycle         : 0.4188
bird            : 0.2848
boat            : 0.2978
bottle          : 0.3248
bus             : 0.3452
car             : 0.3970
cat             : 0.0805
chair           : 0.3393
cow             : 0.4999
diningtable     : 0.1703
dog             : 0.2019
horse           : 0.3035
motorbike       : 0.3662
person          : 0.5565
pottedplant     : 0.4436
sheep           : 0.1996
sofa            : 0.2630
train           : 0.3749
tvmonitor       : 0.4676
```

Following is the soruce-only score of clipart1k:
```yaml
 mAP: 0.2754
aeroplane       : 0.1798
bicycle         : 0.4767
bird            : 0.2161
boat            : 0.1275
bottle          : 0.2338
bus             : 0.6437
car             : 0.3147
cat             : 0.1322
chair           : 0.3185
cow             : 0.1364
diningtable     : 0.1931
dog             : 0.1273
horse           : 0.2536
motorbike       : 0.4130
person          : 0.3196
pottedplant     : 0.3662
sheep           : 0.0909
sofa            : 0.2208
train           : 0.4274
tvmonitor       : 0.3165
```

I just do not know there was anything wrong with my experiment or anything else, because my result(Map50=0.3296) was much higher than your papers (mAP50=19.8)
